// Contract Configuration
// Auto-generated by deployment script

export const CONTRACT_CONFIG = {
  factoryAddress: '0xb8b3a26AD1a1213Cf8c0509442E7B0C766Bd1ebB' as `0x${string}`,
  priceOracleAddress: '0xa4354930CecCCCE2CbE122Fb5ABb156014E83FD9' as `0x${string}`,
  chainId: 11155111,
  chainName: 'sepolia',
};

// Chainlink Price Feeds
export const CHAINLINK_FEEDS = {
  ethUsd: '0x694AA1769357215DE4FAC081bf1f309aDC325306',
  btcUsd: '0x1b44F3514812d835EB1BDB0acB33d3fA3351Ee43',
  solUsd: 'Not available',
};

// Test Markets (for development)
export const TEST_MARKETS = {
  eventMarket: '0x9bb07F43b8F22aFc91Ffb55d9b65EF2CD2e7e014',
  priceMarket: '0xD4c2D12C34afc56E6ca8069b8639F1A4f39F6628',
};
